---
abstract: 'DZIL Author Bundle for BBYRD'
author:
  - 'Brendan Byrd <BBYRD@CPAN.org>'
build_requires:
  Test::CheckDeps: 0.002
  Test::More: 0.94
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.130880'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-BBYRD
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Dist::Zilla::MintingProfile::Author::BBYRD:
    file: lib/Dist/Zilla/MintingProfile/Author/BBYRD.pm
    version: 0.97
  Dist::Zilla::PluginBundle::Author::BBYRD:
    file: lib/Dist/Zilla/PluginBundle/Author/BBYRD.pm
    version: 0.97
  Pod::Weaver::PluginBundle::Author::BBYRD:
    file: lib/Pod/Weaver/PluginBundle/Author/BBYRD.pm
    version: 0.97
requires:
  Dist::Zilla: 4.300035
  Dist::Zilla::App::Command::podpreview: 0.002
  Dist::Zilla::Plugin::CheckExtraTests: 0.011
  Dist::Zilla::Plugin::CheckPrereqsIndexed: 0.009
  Dist::Zilla::Plugin::Clean: 0.07
  Dist::Zilla::Plugin::ContributorsFromGit: 0.006
  Dist::Zilla::Plugin::CopyFilesFromBuild: 0.103510
  Dist::Zilla::Plugin::GitFmtChanges: 0.005
  Dist::Zilla::Plugin::InstallGuide: 1.200000
  Dist::Zilla::Plugin::InstallRelease: 0.008
  Dist::Zilla::Plugin::MetaProvides::Package: 1.14000002
  Dist::Zilla::Plugin::MetaResourcesFromGit: 1.103620
  Dist::Zilla::Plugin::NoTabsTests: 0.01
  Dist::Zilla::Plugin::OurPkgVersion: 0.004000
  Dist::Zilla::Plugin::PodWeaver: 3.101641
  Dist::Zilla::Plugin::ReadmeAnyFromPod: 0.131500
  Dist::Zilla::Plugin::ReportPhase: 0
  Dist::Zilla::Plugin::Test::CPAN::Meta::JSON: 0.003
  Dist::Zilla::Plugin::Test::CheckDeps: 0.006
  Dist::Zilla::Plugin::Test::CheckManifest: 0.04
  Dist::Zilla::Plugin::Test::Compile: 2.002
  Dist::Zilla::Plugin::Test::DistManifest: 2.000003
  Dist::Zilla::Plugin::Test::EOL: 0.07
  Dist::Zilla::Plugin::Test::MinimumVersion: 2.000005
  Dist::Zilla::Plugin::Test::Portability: 2.000004
  Dist::Zilla::Plugin::Test::ReportPrereqs: 0.006
  Dist::Zilla::Plugin::Test::Synopsis: 2.000003
  Dist::Zilla::Plugin::Test::Version: 0.002004
  Dist::Zilla::Plugin::TravisYML: 1.02
  Dist::Zilla::PluginBundle::Git: 2.013
  Dist::Zilla::PluginBundle::Git::CheckFor: 0.006
  Dist::Zilla::PluginBundle::GitHub: 0.34
  Dist::Zilla::PluginBundle::Prereqs: 0.92
  Dist::Zilla::Role::PluginBundle::Merged: 0.92
  Dist::Zilla::Stash::PAUSE::Encrypted: 0.003
  Moose: 2.0802
  Pod::Coverage::TrustPod: 0.100002
  Pod::Elemental::Transformer::List: 0.101620
  Pod::Weaver: 3.101638
  Pod::Weaver::Plugin::Encoding: 0.01
  Pod::Weaver::Plugin::WikiDoc: 0.093002
  Pod::Weaver::Section::Availability: 1.20
  Pod::Weaver::Section::Contributors: 0.006
  Pod::Weaver::Section::Support: 1.001
  Test::CPAN::Meta::JSON: 0.14
  autovivification: 0.11
  indirect: 0.30
  multidimensional: 0.011
  perl: v5.10.1
  sanity: 0.96
resources:
  X_irc: irc://irc.perl.org/#distzilla
  bugtracker: https://github.com/SineSwiper/Dist-Zilla-PluginBundle-Author-BBYRD/issues
  homepage: https://github.com/SineSwiper/Dist-Zilla-PluginBundle-Author-BBYRD/wiki
  repository: git://github.com/SineSwiper/Dist-Zilla-PluginBundle-Author-BBYRD.git
version: 0.97
x_Dist_Zilla:
  perl:
    version: 5.014002
  plugins:
    -
      class: Dist::Zilla::Plugin::ReportPhase
      name: '@Filter/ReportPhase'
      version: 0.03
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/MakeMaker'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ModuleShareDirs
      name: '@Filter/ModuleShareDirs'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Filter/Git::NextVersion'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Filter/Git::GatherDir'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: '@Filter/OurPkgVersion'
      version: 0.004000
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::GitFmtChanges
      name: '@Filter/GitFmtChanges'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Filter/ReadmePodInRoot'
      version: 0.131500
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Filter/ReadmeTextInBuild'
      version: 0.131500
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Filter/ReadmeHTMLInBuild'
      version: 0.131500
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Filter/InstallGuide'
      version: 1.200000
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@Filter/Test::Compile'
      version: 2.002
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: '@Filter/RunExtraTests'
      version: 0.011
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@Filter/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::Test::EOL
      name: '@Filter/Test::EOL'
      version: 0.07
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: '@Filter/Test::CPAN::Meta::JSON'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::Test::CheckDeps
      name: '@Filter/Test::CheckDeps'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@Filter/Test::Portability'
      version: 2.000004
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Filter/Test::MinimumVersion'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Filter/Test::ReportPrereqs'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Test::CheckManifest
      name: '@Filter/Test::CheckManifest'
      version: 0.04
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: '@Filter/Test::DistManifest'
      version: 2.000003
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: '@Filter/Test::Version'
      version: 0.002004
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Filter/CheckPrereqsIndexed'
      version: 0.009
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Filter/MetaNoIndex'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Filter/MetaProvides::Package'
      version: 1.14000002
    -
      class: Dist::Zilla::Plugin::MetaResourcesFromGit
      name: '@Filter/MetaResourcesFromGit'
      version: 1.103620
    -
      class: Dist::Zilla::Plugin::ContributorsFromGit
      name: '@Filter/ContributorsFromGit'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@Filter/CopyFilesFromBuild'
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@Filter/Git::CheckFor::CorrectBranch'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@Filter/Git::CommitBuild'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/@Git/Check'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/@Git/Commit'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/@Git/Tag'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/@Git/Push'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@Filter/GitHub::Update'
      version: 0.34
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Filter/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Clean
      name: '@Filter/Clean'
      version: 0.07
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: MinimumPerl
      version: 1.003
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::LatestPrereqs
      name: LatestPrereqs
      version: 0.4
    -
      class: Dist::Zilla::Plugin::PrereqsClean
      name: PrereqsClean
      version: 0.92
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300035
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300035
x_contributors:
  - 'Brendan Byrd <Perl@ResonatorSoft.org>'
