---
abstract: 'DZIL Author Bundle for BBYRD'
author:
  - 'Brendan Byrd <BBYRD@CPAN.org>'
build_requires:
  Test::CheckDeps: 0.006
  Test::More: 0.94
configure_requires:
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.130880'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-BBYRD
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Dist::Zilla::MintingProfile::Author::BBYRD:
    file: lib/Dist/Zilla/MintingProfile/Author/BBYRD.pm
    version: 0.99
  Dist::Zilla::PluginBundle::Author::BBYRD:
    file: lib/Dist/Zilla/PluginBundle/Author/BBYRD.pm
    version: 0.99
  Pod::Weaver::PluginBundle::Author::BBYRD:
    file: lib/Pod/Weaver/PluginBundle/Author/BBYRD.pm
    version: 0.99
requires:
  Dist::Zilla: 4.300038
  Dist::Zilla::App::Command::podpreview: 0.003
  Dist::Zilla::Plugin::Bootstrap::lib: 0.04000000
  Dist::Zilla::Plugin::CheckExtraTests: 0.011
  Dist::Zilla::Plugin::CheckPrereqsIndexed: 0.009
  Dist::Zilla::Plugin::Clean: 0.07
  Dist::Zilla::Plugin::ContributorsFromGit: 0.006
  Dist::Zilla::Plugin::CopyFilesFromBuild: 0.103510
  Dist::Zilla::Plugin::GitFmtChanges: 0.005
  Dist::Zilla::Plugin::InstallGuide: 1.200000
  Dist::Zilla::Plugin::InstallRelease: 0.008
  Dist::Zilla::Plugin::MetaProvides::Package: 1.14000003
  Dist::Zilla::Plugin::MetaResourcesFromGit: 1.103620
  Dist::Zilla::Plugin::NoTabsTests: 0.01
  Dist::Zilla::Plugin::OurPkgVersion: 0.005000
  Dist::Zilla::Plugin::PodWeaver: 3.101642
  Dist::Zilla::Plugin::ReadmeAnyFromPod: 0.131500
  Dist::Zilla::Plugin::ReportPhase: 0
  Dist::Zilla::Plugin::Test::CPAN::Meta::JSON: 0.003
  Dist::Zilla::Plugin::Test::CheckDeps: 0.007
  Dist::Zilla::Plugin::Test::CheckManifest: 0.04
  Dist::Zilla::Plugin::Test::Compile: 2.029
  Dist::Zilla::Plugin::Test::DistManifest: 2.000004
  Dist::Zilla::Plugin::Test::EOL: 0.08
  Dist::Zilla::Plugin::Test::MinimumVersion: 2.000005
  Dist::Zilla::Plugin::Test::Portability: 2.000005
  Dist::Zilla::Plugin::Test::ReportPrereqs: 0.006
  Dist::Zilla::Plugin::Test::Synopsis: 2.000004
  Dist::Zilla::Plugin::Test::Version: 0.002004
  Dist::Zilla::Plugin::TravisYML: 1.04
  Dist::Zilla::PluginBundle::Git: 2.014
  Dist::Zilla::PluginBundle::Git::CheckFor: 0.006
  Dist::Zilla::PluginBundle::GitHub: 0.35
  Dist::Zilla::PluginBundle::Prereqs: 0.92
  Dist::Zilla::Role::PluginBundle::Merged: 1.00
  Dist::Zilla::Role::PluginBundle::PluginRemover: 0.102
  Dist::Zilla::Stash::PAUSE::Encrypted: 0.003
  Moose: 2.1005
  Pod::Coverage::TrustPod: 0.100002
  Pod::Elemental::Transformer::List: 0.101620
  Pod::Weaver: 3.101638
  Pod::Weaver::Plugin::Encoding: 0.01
  Pod::Weaver::Plugin::WikiDoc: 0.093002
  Pod::Weaver::Section::Availability: 1.20
  Pod::Weaver::Section::Contributors: 0.006
  Pod::Weaver::Section::Support: 1.001
  Test::CPAN::Meta::JSON: 0.15
  autovivification: 0.12
  indirect: 0.31
  multidimensional: 0.011
  perl: v5.10.1
  sanity: 1.02
resources:
  X_irc: irc://irc.perl.org/#distzilla
  bugtracker: https://github.com/SineSwiper/Dist-Zilla-PluginBundle-Author-BBYRD/issues
  homepage: https://github.com/SineSwiper/Dist-Zilla-PluginBundle-Author-BBYRD/wiki
  repository: git://github.com/SineSwiper/Dist-Zilla-PluginBundle-Author-BBYRD.git
version: 0.99
x_Dist_Zilla:
  perl:
    version: 5.014002
  plugins:
    -
      class: Dist::Zilla::Plugin::Bootstrap::lib
      config:
        Dist::Zilla::Role::Bootstrap:
          distname: Dist-Zilla-PluginBundle-Author-BBYRD
          fallback: 1
          try_built: ~
      name: Bootstrap::lib
      version: 0.04000000
    -
      class: Dist::Zilla::Plugin::ReportPhase
      name: '@Author::BBYRD/ReportPhase'
      version: 0.03
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::BBYRD/MakeMaker'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::BBYRD/Git::NextVersion'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Author::BBYRD/Git::GatherDir'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: '@Author::BBYRD/OurPkgVersion'
      version: 0.005000
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Author::BBYRD/PodWeaver'
      version: 3.101642
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::BBYRD/PruneCruft'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::GitFmtChanges
      name: '@Author::BBYRD/GitFmtChanges'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::BBYRD/ManifestSkip'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::BBYRD/Manifest'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::BBYRD/License'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::BBYRD/ReadmePodInRoot'
      version: 0.131500
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::BBYRD/ReadmeTextInBuild'
      version: 0.131500
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::BBYRD/ReadmeHTMLInBuild'
      version: 0.131500
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Author::BBYRD/InstallGuide'
      version: 1.200000
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::BBYRD/ExecDir'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Author::BBYRD/Test::Compile'
      version: 2.029
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::BBYRD/PodSyntaxTests'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: '@Author::BBYRD/RunExtraTests'
      version: 0.011
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@Author::BBYRD/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::Test::EOL
      name: '@Author::BBYRD/Test::EOL'
      version: 0.08
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: '@Author::BBYRD/Test::CPAN::Meta::JSON'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::Test::CheckDeps
      name: '@Author::BBYRD/Test::CheckDeps'
      version: 0.007
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@Author::BBYRD/Test::Portability'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::BBYRD/Test::MinimumVersion'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Author::BBYRD/Test::ReportPrereqs'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Test::CheckManifest
      name: '@Author::BBYRD/Test::CheckManifest'
      version: 0.04
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: '@Author::BBYRD/Test::DistManifest'
      version: 2.000004
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Author::BBYRD/CheckPrereqsIndexed'
      version: 0.009
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::BBYRD/MetaConfig'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::BBYRD/MetaJSON'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::BBYRD/MetaYAML'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Author::BBYRD/MetaNoIndex'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Author::BBYRD/MetaProvides::Package'
      version: 1.14000003
    -
      class: Dist::Zilla::Plugin::MetaResourcesFromGit
      name: '@Author::BBYRD/MetaResourcesFromGit'
      version: 1.103620
    -
      class: Dist::Zilla::Plugin::ContributorsFromGit
      name: '@Author::BBYRD/ContributorsFromGit'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@Author::BBYRD/CopyFilesFromBuild'
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::TravisYML
      name: '@Author::BBYRD/TravisYML'
      version: 1.04
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@Author::BBYRD/Git::CheckFor::CorrectBranch'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@Author::BBYRD/Git::CommitBuild'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::BBYRD/@Git/Check'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::BBYRD/@Git/Commit'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::BBYRD/@Git/Tag'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::BBYRD/@Git/Push'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@Author::BBYRD/GitHub::Update'
      version: 0.35
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::BBYRD/TestRelease'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::BBYRD/ConfirmRelease'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::BBYRD/UploadToCPAN'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::BBYRD/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Clean
      name: '@Author::BBYRD/Clean'
      version: 0.07
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: MinimumPerl
      version: 1.003
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::LatestPrereqs
      name: LatestPrereqs
      version: 0.4
    -
      class: Dist::Zilla::Plugin::PrereqsClean
      name: PrereqsClean
      version: 0.92
    -
      class: Dist::Zilla::Plugin::ModuleShareDirs
      name: ModuleShareDirs
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300038
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300038
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300038
x_contributors:
  - 'Brendan Byrd <bbyrd@cpan.org>'
